
service: test2
provider:
      name: aws
      runtime: nodejs12.x
      iamRoleStatements:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource:
                   Fn::Join:
                     - ""
                     - - "arn:aws:dynamodb:*:*:table/"
                       - Ref: UserGqlDynamoDbTable
                       - Ref: OrderGqlDynamoDbTable
                       - Ref: TaskGqlDynamoDbTable

functions:
      queryhandler:
        handler: handler/handler.queryhandler
        events:
        - http:
            path: graphql
            method: post
            cors: true
        environment:
          USER_TABLE: test00_users
          ORDER_TABLE: test00_orders
          TASK_TABLE : test00_tasks
      playground:
        handler: handler/handler.queryhandler
        events:
        - http:
            path: playground
            method: get
      
       
          

resources:
      Resources:
        UserGqlDynamoDbTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: test00_users
            AttributeDefinitions:
              - AttributeName: dummy
                AttributeType: S
              - AttributeName: _id
                AttributeType: S
              - AttributeName: createdAt
                AttributeType: S
              - AttributeName: status
                AttributeType: S
              - AttributeName: position
                AttributeType: S
              - AttributeName: username
                AttributeType: S
            KeySchema:
              - AttributeName: dummy
                KeyType: HASH
              - AttributeName: _id
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
            LocalSecondaryIndexes:
              - IndexName: createdAt_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: createdAt
                  KeyType: RANGE
              - IndexName: username_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: username
                  KeyType: RANGE
              - IndexName: status_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: status
                  KeyType: RANGE
              - IndexName: position_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: position
                  KeyType: RANGE  
            ProjectionType: ALL
        OrderGqlDynamoDbTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: test00_orders
            AttributeDefinitions:
              - AttributeName: dummy
                AttributeType: S
              - AttributeName: _id
                AttributeType: S
              - AttributeName: createdAt
                AttributeType: S
              - AttributeName: username
                AttributeType: S
              - AttributeName: menu
                AttributeType: S
              - AttributeName: hi
                AttributeType: S
            KeySchema:
              - AttributeName: dummy
                KeyType: HASH
              - AttributeName: _id
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
            LocalSecondaryIndexes:
              - IndexName: createdAt_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: createdAt
                  KeyType: RANGE
              - IndexName: username_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: username
                  KeyType: RANGE
              - IndexName: menu_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: menu
                  KeyType: RANGE
              - IndexName: hi_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: hi
                  KeyType: RANGE  
            ProjectionType: ALL
        TaskGqlDynamoDbTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: test00_tasks
            AttributeDefinitions:
              - AttributeName: dummy
                AttributeType: S
              - AttributeName: _id
                AttributeType: S
              - AttributeName: createdAt
                AttributeType: S
              - AttributeName: creater
                AttributeType: S
              - AttributeName: title
                AttributeType: S
            KeySchema:
              - AttributeName: dummy
                KeyType: HASH
              - AttributeName: _id
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
            LocalSecondaryIndexes:
              - IndexName: createdAt_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: createdAt
                  KeyType: RANGE
              - IndexName: creater_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: creater
                  KeyType: RANGE
              - IndexName: title_index
                KeySchema:
                - AttributeName: dummy
                  KeyType: HASH
                - AttributeName: title
                  KeyType: RANGE
            ProjectionType: ALL
        
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
